<a href="https://colab.research.google.com/github/Andrzej-Langner/data-science-bootcamp/blob/main/Lekcja13_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.6'

In [ ]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [ ]:
v2 = np.array([-10, 10,13])
np.linalg.norm(v2)

19.209372712298546

In [ ]:
p = np.array([3, 0])
q = np.array([0, 4])

np.linalg.norm(p-q)

In [ ]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)

5.0990195135927845

In [ ]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])

Rozwiązanie układu równań

In [2]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [4]:
#Wektor wyrazów wolnych
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [5]:
# Znajdujemy macierz odwrotną do A
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X

array([[1.],
       [2.]])